### PR TITLE
g++12 / libssl 3.0 support + backgroundTask in SearchForMatchingBlocks

### PR DESCRIPTION
**Pull request by jcollonville**
Hello, 
A possible deadlock was found when bbstored streams a very large file index and that the client drop the connection.
In this case IOStream::CopyStreamTo has initialited the write with an infinite timeout, thus when SocketStreamTLS::WaitWhenRetryRequired if hitted it may hang in there.

Adding Timeout checks on TSL read/write appears to be safer...

### CODE REVIEW

**Comment by qris** [comment]
Thanks for the report and the pull request! I am tempted to just merge it, but it doesn't seem like the cleanest possible solution, because it makes Read() no longer honour the supplied Timeout argument (if it's infinite). I'd prefer to change the call site that's failing to pass a valid timeout to do so instead. Do you have a backtrace of the deadlock by any chance?

**Comment by qris** [comment]
The server daemon `BackupStoreDaemon` always seems to set the default timeout of the `BackupProtocolServer` that it's using to communicate with the client to a sensible value (15 minutes) before calling `server.DoServer`:

```
server.SetTimeout(BACKUP_STORE_TIMEOUT);
```

This timeout is *generally* honoured when writing. The only place I've found so far where it's not is in:

```mapConn->WriteAllBuffered();```

which fails to pass a timeout to `WriteAllBuffered`, so Infinite is used by default. This could be the problem, although I'm a little surprised that the client disappeared while we were sending the last few bytes to it (it's possible but unlikely).

**Comment by jcollonville** [comment]
Indeed, I was not fan either from forcing a timeout here, but more detailed here is what I found :

**Comment by jcollonville** [comment]
Indeed, I was not fan either from forcing a timeout here, but more detailed here is what I found : 

So the lock occurs in ```BackupProtocolGetBlockIndexByName::DoCommand()```
when the file is opened for reading ```std::auto_ptr<IOStream> stream(rContext.OpenObject(objectID));``` the Write methode of ```IOStream``` has a default parameter of IOStream::TimeOutInfinite which, from what I found, causes the issue.

I got a rare backtrace when it happened, but that's not very helpful :
```#0  SocketStreamTLS::Write (this=0x5555557b6920, pBuffer=0x5555557c6d70, NBytes=4096, Timeout=-1) at lib/server/SocketStreamTLS.cpp:359
#1  0x00005555556d20a7 in IOStream::CopyStreamTo (this=this@entry=0x5555557cf130, rCopyTo=..., Timeout=900000, BufferSize=BufferSize@entry=4096) at lib/common/IOStream.cpp:221
#2  0x00005555556a6f36 in Protocol::SendStream (this=this@entry=0x7fffffffc820, rStream=...) at /usr/include/c++/12/backward/auto_ptr.h:185
#3  0x0000555555648954 in BackupProtocolServer::DoServer (this=this@entry=0x7fffffffc800, rContext=...) at lib/backupstore/autogen_BackupProtocol.cpp:2935
#4  0x00005555555cbe8c in BackupStoreDaemon::Connection2 (this=0x7fffffffdb50, apStream=...) at lib/bbstored/BackupStoreDaemon.cpp:359
#5  0x00005555555cc820 in BackupStoreDaemon::Connection (this=<optimised out>, apStream=...) at lib/bbstored/BackupStoreDaemon.cpp:283
#6  0x00005555555ce65a in ServerTLS<2201, 128, true>::HandleConnection (this=0x7fffffffdb50, apStream=...) at lib/server/ServerTLS.h:72
#7  0x00005555555d1823 in ServerStream<SocketStreamTLS, 2201, 128, true>::Run2 (this=this@entry=0x7fffffffdb50, rChildExit=@0x7fffffffd25f: false) at lib/server/ServerStream.h:312
#8  0x00005555555d35e7 in ServerTLS<2201, 128, true>::Run2 (this=0x7fffffffdb50, rChildExit=@0x7fffffffd25f: false) at lib/server/ServerTLS.h:65
#9  0x00005555555cd22b in ServerStream<SocketStreamTLS, 2201, 128, true>::Run (this=this@entry=0x7fffffffdb50) at lib/server/ServerStream.h:79
#10 0x00005555555cad81 in BackupStoreDaemon::Run (this=0x7fffffffdb50) at lib/bbstored/BackupStoreDaemon.cpp:250
#11 0x000055555569d1f5 in Daemon::Main (this=0x7fffffffdb50, rConfigFileName=...) at lib/server/Daemon.cpp:713
#12 0x00005555555c8d1b in main (argc=6, argv=0x7fffffffe228) at bin/bbstored/bbstored.cpp:27
```

**Comment by qris** [comment]
On the contrary, that is very helpful. We can see that a sensible timeout was passed to CopyStreamTo(). Looking at that function, it clearly fails to pass the timeout on to Write(). I also needed to make sure that Write() would always raise an appropriate exception if a timeout occurs in WaitWhenRetryRequired(). Hopefully #119 will fix the problem.

**Comment by jcollonville** [comment]
Urgh! I wonder how I missed that ! my c++ is too rusty...
Thanks for the nice fix :+1:

**Comment by jcollonville** [comment]
I had some other changes that would be nice to have here: compilation for g++12 and libssl 3.0 but the previous PR was closed when resosafe branch was deleted.
Anyway, when trying to open a new PR for thoses changes github always brings me back to #118 ...

**Comment by qris** [comment]
Yep, I saw those. Your commits are still here and safe on your branch (linked to this PR). I will look at them soon. I'd like to have CI for the compilation fixes at least. On which platform/distro/version did you notice the failures with g++12?

**Comment by jcollonville** [comment]
I'm building on Ubuntu 22.10On Dec 2, 2022 22:41, Chris Wilson ***@***.***> wrote:
Yep, I saw those. Your commits are still here and safe on your branch (linked to this PR). I will look at them soon. I'd like to have CI for the compilation fixes at least. On which platform/distro/version did you notice the failures with g++12?

**Pull request closed without merging**
