### PR TITLE
Improve travis output by turning the single command to multiple steps

### PR DESCRIPTION
**Pull request by cmorty**

### CODE REVIEW

**Comment by cmorty** [comment]
Yey, concurrency/performance issues. Someone should target or exclude them from travis. :/

**Comment by qris** [comment]
Sorry, I don't understand these concurrency issues, do you? Will this cause the travis CI tests to fail always, or is this a random failure?

**Comment by qris** [comment]
OK, I understand a bit better now. the error was actually in the debug tests, half way down. Two tests failed: 

    NOTICE:  test result: FAILED: test_ssl_keepalives
    NOTICE:  test result: FAILED: test_sync_allow_script_can_pause_backup

Both are timing-dependent tests, and therefore not 100% reliable. Since I can no longer trigger another build in Travis itself, I will merge this and we'll see if the tests pass then. If not, I'll revert it until we make it work reliably.

**Comment by cmorty** [comment]
@qris You should be able to restart a travis-buid. At least I can for my repos last time I checked. 
I didn't really look into the test-infrastructure yet, but I'd suggest doing two things:
 * Make sure that the timing-sensitive tests do not fail / remove them from CI. Travis sets the environment-variable 'CI' to true. Maybe this can be used to choose more timing-tolerant settings.
 * Run things in parallel as described in http://docs.travis-ci.com/user/speeding-up-the-build/. The first step would be to split up in 'debug' and 'release'. I can do that as a first step. Later it might also be a good idea to create about 4 or 5 subgroups of tests. Having to wait 30 minutes can be very frustrating.

**Comment by qris** [comment]
Luckily it passed this time :) And I found the rebuild button that I didn't know existed, thanks :)

I think it would be good to refactor the timing-based tests to reduce their timing dependency. We have much better ability to make tests that replace parts of the backup daemon now, and we could use this to check the individual parts that are supposed to have timing effects (e.g. SSL keepalives being sent on time).

I'm reluctant to disable tests completely, but it is an option. If you could split into debug and release builds using the build matrix, that would be great.

**Comment by cmorty** [comment]
Already working on it. It seems though that speeding up the build-process by running make with -j4 does not seem to work.

As for the timing-critical things: Maybe it's possible to repeat them, lets say 3 times, before they fail.

**Comment by qris** [comment]
The build is automatically parallelised by the build scripts:

    16 processors detected, will set make to perform concurrent jobs

I will look at [enabling ccache](http://docs.travis-ci.com/user/caching/) which should speed up compilation dramatically.

**Comment by cmorty** [comment]
No worries, I was only reaching for the low hanging fruits. ;) IMO getting those timing-issues under control is more important.

**Pull request merged**
